/**
 * Interface لسجل دفتر النصوص
 */
export interface TextbookEntry {
  id: string;
  date: string; // تاريخ الحصة (YYYY-MM-DD)
  startTime: string; // توقيت بداية الحصة (HH:MM)
  duration: number; // مدة الحصة بالساعات
  sectionId: string; // معرف القسم
  sectionName: string; // اسم القسم (للعرض)
  
  // تفصيل الموضوع
  lessonTitle: string; // عنوان الدرس
  sessionNumber: number; // رقم الحصة للدرس (1, 2, 3...)
  completedStages: CompletedStage[]; // المراحل المُنجزة
  lessonContent: string; // النص المُولّد تلقائياً + التعديلات اليدوية
  
  // التوقيع والملاحظات
  teacherSignature: string; // توقيع المعلم
  notes: string; // ملاحظات إضافية
  
  // معلومات النظام
  isAutoGenerated: boolean; // هل تم إنتاجه تلقائياً أم يدوياً
  originalLessonId?: string; // معرف الحصة الأصلية (إن وجد)
  createdAt: string; // تاريخ الإنشاء
  updatedAt: string; // تاريخ آخر تحديث
}

/**
 * Interface للمراحل المُنجزة
 */
export interface CompletedStage {
  id: string;
  title: string;
  isCompleted: boolean;
  completionDate?: string;
}

/**
 * Interface لفلترة سجلات دفتر النصوص
 */
export interface TextbookFilter {
  sectionId?: string; // 'all' للكل أو معرف قسم محدد
  dateFrom?: string; // تاريخ البداية (YYYY-MM-DD)
  dateTo?: string; // تاريخ النهاية (YYYY-MM-DD)
  teacherSignature?: string; // فلترة حسب المعلم
}

/**
 * Interface لإحصائيات دفتر النصوص
 */
export interface TextbookStats {
  totalEntries: number; // إجمالي السجلات
  completedLessons: number; // الدروس المكتملة
  autoGeneratedEntries: number; // السجلات المُولّدة تلقائياً
  manualEntries: number; // السجلات اليدوية
  sectionsStats: {
    sectionId: string;
    sectionName: string;
    entryCount: number;
  }[];
}