const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const TextbookEntry = sequelize.define('TextbookEntry', {
  id: {
    type: DataTypes.STRING,
    primaryKey: true,
    allowNull: false,
  },
  date: {
    type: DataTypes.DATEONLY, // تاريخ فقط بدون وقت
    allowNull: false,
  },
  startTime: {
    type: DataTypes.STRING, // HH:MM
    allowNull: false,
  },
  duration: {
    type: DataTypes.FLOAT, // مدة بالساعات (يمكن أن تكون 1.5 مثلاً)
    allowNull: false,
    defaultValue: 1.0,
  },
  sectionId: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  sectionName: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  
  // تفصيل الموضوع
  lessonTitle: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  sessionNumber: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 1,
  },
  completedStages: {
    type: DataTypes.JSON, // مصفوفة المراحل المُنجزة
    allowNull: true,
    defaultValue: [],
  },
  lessonContent: {
    type: DataTypes.TEXT, // النص الكامل لتفصيل الموضوع
    allowNull: false,
  },
  
  // التوقيع والملاحظات
  teacherSignature: {
    type: DataTypes.STRING,
    allowNull: true,
    defaultValue: 'بشيري نبيل', // توقيع افتراضي
  },
  notes: {
    type: DataTypes.TEXT,
    allowNull: true,
  },
  
  // معلومات النظام
  isAutoGenerated: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: true,
  },
  originalLessonId: {
    type: DataTypes.STRING,
    allowNull: true, // قد يكون null للسجلات اليدوية
  },
}, {
  timestamps: true, // سيضيف createdAt و updatedAt تلقائياً
  indexes: [
    // فهارس لتحسين الأداء
    {
      fields: ['date']
    },
    {
      fields: ['sectionId']
    },
    {
      fields: ['date', 'sectionId']
    },
    {
      fields: ['isAutoGenerated']
    }
  ]
});

module.exports = TextbookEntry;